### ISSUE TITLE
Data from inpatients 2022 uploaded

### ISSUE THREAD

**Issue by clara-miguel** [metapsy-project/data-inpatients#1]
@MathiasHarrer please find the data for inpatients uploaded here.

**Comment by MathiasHarrer** [comment]
Wonderful @clara-miguel, thanks!

**Comment by MathiasHarrer** [comment]
I will let you know once I am ready to do the first release together 🚀

**Comment by clara-miguel** [comment]
I will work further on the documentation of the database towards the end of the week (methodological decisions, search strings, RoB etc.). I notice that I uploaded it as excel file, although it should be .csv. Sorry about that! Also, the effect sizes are not calculated due to the proposed changes in the package. Let me know if I can help with that :)

**Comment by MathiasHarrer** [comment]
No problem! Feel free to let me know if you have questions while compiling the `metadata` folder (like in the [data-template](https://github.com/metapsy-project/data-template/tree/master/metadata) folder).

I expect that I will have time to implement the little changes to `metapsyTools` in the beginning of next week. After that, we can talk about the first release.

Looking at the data you uploaded: `specification_arm1/2` should still be changed to `multi_arm1/2`, right?

**Comment by clara-miguel** [comment]
Oh yes sorry about that! I forgot to change that, with the back and forth!

**Comment by MathiasHarrer** [comment]
Alrighty, found some time now :)
I think the changes should be implemented everywhere now; see e.g.
- [The Metapsy Data Standard Documentation](https://docs.metapsy.org/data-preparation/format/#standard-variables)
- newly released [data-template](https://github.com/metapsy-project/data-template) (v22.8.6).

the new (unreleased) version of `metapsyTools` has also been adapted to take account of these changes. This means that I can calculate the ES for you now. Should I do that, based on the excel you uploaded?

Otherwise, from my perspective, all we still need to do is to pre-format this repo like the example in `data-template` (so add the metadata), and then we can release :)

**Comment by MathiasHarrer** [comment]
P.S. I also had a brief look at the excel as-is; it's generally very close to the requirements, but 1-2 tiny tweaks are still necessary. Should I simply take care of that, document what I changed & then we talk about it in our big release meeting?

**Comment by clara-miguel** [comment]
Thanks a lot! Maybe it is better that you implement those tiny changes and let me know what you changed? that way we can learn for the rest of the datasets :) I can take care of the data-template, so that I learn how to format that. 
@cyplessen look Yves, metapsyTools is also now adapted. Yesterday we were talking just about this!

**Comment by clara-miguel** [comment]
I created the metadata files in a not so efficient way, but I hope they are OK. I did not know how to clone your data-template repository, so I added them one by one :(((
I added a few more files that I think should be necessary to all datasets (comparisons, RoB, and outcome calculation types). What I do not know how to do is to automatically create the .json files for the references and the variable description, but maybe we can do it together on Friday?

**Comment by MathiasHarrer** [comment]
That's not a problem. The way Lea showed you to use Github is very sophisticated and how your "supposed" to use Git. For the data repos here, there is a much simpler way to do this, in which you do not need to use sourcetree at all. I can show you on Friday how that works.

**Comment by MathiasHarrer** [comment]
@clara-miguel It is possible to write JSONs in R (but of course not only there, there are also Excel plugins).
So one way is import the excel file with the study name `study` and the variable containing the reference into R, and then to use this code:

```r
# Download and load jsonlite package
# install.packages("RJSONIO")
library(RJSONIO)

# Create a "fake" data frame with study and citation
data <- data.frame(
  study = c("Quine, 1976", "Nagel, 1974", "Pennycook, 2015"), 
  ref = c("Orman Quine, W. V. (1976). Two dogmas of empiricism. In Can theories be refuted? (pp. 41-64). Springer, Dordrecht.",
          "Nagel, T. (1974). What is it like to be a bat?. The philosophical review, 83(4), 435-450.",
          "Pennycook, G., Cheyne, J. A., Barr, N., Koehler, D. J., & Fugelsang, J. A. (2015). On the reception and detection of pseudo-profound bullshit. Judgment and Decision making, 10(6), 549-563."))

# Extract the column with the references
references <- data$ref

# Give the references the name of the associated study
names(references) <- data$study

# Make the JSON
JSON <- RJSONIO::toJSON(as.list(references))

# Save the JSON file
write(JSON, "references.json")
```

**Comment by MathiasHarrer** [comment]
To write the variable description, it might be helpful to use an online editor like this: https://jsoneditoronline.org/#left=cloud.ba97f9f771a64f31b4042135b4b22c46

The editor automatically tells you when there is a formatting issue.
